In [81]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
from pandas.tools.plotting import scatter_matrix
import random
from sklearn.cross_validation import train_test_split
import score_predictions
import submit_predictions

# style matplotlib
import seaborn as se

# Load submit_predictions.py
import submit_predictions

# import 'bank-full_2016.csv' into a DataFrame
test = pd.DataFrame.from_csv('fellows-test.csv', index_col=False)
train = pd.read_csv('fellows-train.csv', index_col=False)

# add the month, the day and the weekofyear
train['Date'] = pd.to_datetime(train['Date'])
train['Month'] = train.Date.dt.month
train['Day'] = train.Date.dt.day
train['WeekOfYear'] = train.Date.dt.weekofyear

month2str = {1:'Jan', 2:'Feb', 3:'Mar', 4:'Apr', 5:'May', 6:'Jun', 7:'Jul', 8:'Aug', 9:'Sept', 10:'Oct', 11:'Nov', 12:'Dec'}
train['monthStr'] = train.Month.map(month2str)

test['Date'] = pd.to_datetime(test['Date'])
test['Month'] = test.Date.dt.month
test['Day'] = test.Date.dt.day
test['WeekOfYear'] = test.Date.dt.weekofyear

train.head(8)

,Store,WeekDay,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,Month,Day,WeekOfYear,monthStr
0,1,5,2015-06-19,4202,487,1,1,0,0,6,19,25,Jun
1,2,5,2015-06-19,4926,544,1,1,0,0,6,19,25,Jun
2,3,5,2015-06-19,8074,797,1,1,0,0,6,19,25,Jun
3,4,5,2015-06-19,9686,1281,1,1,0,0,6,19,25,Jun
4,5,5,2015-06-19,5711,610,1,1,0,0,6,19,25,Jun
5,6,5,2015-06-19,5464,622,1,1,0,0,6,19,25,Jun
6,7,5,2015-06-19,9677,1030,1,1,0,0,6,19,25,Jun
7,8,5,2015-06-19,6773,690,1,1,0,0,6,19,25,Jun

In [85]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor, RandomForestRegressor

# Train Tree based classifier 
train_X = train[train.columns.difference(["Sales"])]
train_Y = train["Sales"]

test_X = test[test.columns.difference(["Sales"])]
# test_Y = test["Sales"]

test.head(8)

# # Fit Random Forest model
# random_forest = RandomForestRegressor(n_estimators=10, max_depth=None, min_samples_split=4)
# random_forest.fit(train_X, train_Y)

# # Predict
# test_Y_random_forest_prediction = random_forest.predict(test_Y)

,Store,WeekDay,Date,Open,Promo,StateHoliday,SchoolHoliday,Month,Day,WeekOfYear
0,1,5,2015-07-31,1,1,0,1,7,31,31
1,2,5,2015-07-31,1,1,0,1,7,31,31
2,3,5,2015-07-31,1,1,0,1,7,31,31
3,4,5,2015-07-31,1,1,0,1,7,31,31
4,5,5,2015-07-31,1,1,0,1,7,31,31
5,6,5,2015-07-31,1,1,0,1,7,31,31
6,7,5,2015-07-31,1,1,0,1,7,31,31
7,8,5,2015-07-31,1,1,0,1,7,31,31

In [76]:
month2str = {1:'Jan', 2:'Feb', 3:'Mar', 4:'Apr', 5:'May', 6:'Jun', \7:'Jul', 8:'Aug', 9:'Sept', 10:'Oct', 11:'Nov', 12:'Dec'}
data['monthStr'] = data.Month.map(month2str)

Regression coefficients :
[  6.33934107e-02  -6.47529384e+02   2.55949233e+03  -1.56711165e+02
   5.97060739e+01   1.05300461e+01  -8.11603072e-02]

ValueError: shapes (46830,8) and (7,) not aligned: 8 (dim 1) != 7 (dim 0)